### ISSUE TITLE
It is no longer working properly, and all examples are not working.

### ISSUE THREAD

**Issue by tzSharing** [pisaiah/ui#14]
It is no longer working properly, and all examples are not working.

A Run Error dialog box always pops up.
![111](https://github.com/user-attachments/assets/726cf420-1258-4723-b1f2-cb525d9fa8f0)

‪D:\v\thirdparty\sokol\sokol_gfx.h

![2024-9-20_1-56-54](https://github.com/user-attachments/assets/43fcec2b-d920-4b4d-928e-75512812d0b5)

```yaml
D:\v>v doctor
V full version: V 0.4.7 63957f2.9a0f4d8
OS: windows, Microsoft Windows 10 רҵ v19045 64 λ
Processor: 4 cpus, 64bit, little endian,

getwd: D:\v
vexe: D:\v\v.exe
vexe mtime: 2024-09-19 17:23:14

vroot: OK, value: D:\v
VMODULES: OK, value: C:\Users\TZ\.vmodules
VTMP: OK, value: C:\Users\TZ\AppData\Local\Temp\v_0

Git version: git version 2.45.1.windows.1
Git vroot status: weekly.2024.36-103-g9a0f4d84
.git/config present: true

CC version: Error: 'cc' is not recognized as an internal or external command,
operable program or batch file.

thirdparty/tcc status: thirdparty-windows-amd64 b425ac82
```
